remade bottom nav with material design
bogdanustyak/KoreanPhraseBook pull request #16
Opened 2018-07-27 16:15 UTC by LyubomurBuryi

2018-07-28 10:25 UTC, khrystynapochynok approved these changes
@LyubomurBuryi please delete comments of old code and merge to develop

2018-07-30 09:02 UTC, bogdanustyak requested changes

2018-07-30 09:02 UTC, bogdanustyak commented on app/src/main/java/com/leoart/koreanphrasebook/ui/MainActivity.kt
> +//        this.bottomMenu = BottomMenu(
pls remove comments

2018-07-30 09:02 UTC, bogdanustyak commented on app/src/main/res/layout/bottom_menu.xml
> +    <!--<ImageView-->
remove this too

2018-07-30 11:05 UTC, bogdanustyak approved these changes

2018-07-30 11:05 UTC, merged